plugins {
    id 'com.android.application'
}

android {
    namespace 'com.kuzia15.puzzle'
    compileSdk 35

    defaultConfig {
        applicationId 'com.kuzia15.puzzle'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '1.0'
    }
}

dependencies {
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'
}